---
- name: Install common packages across all os (Linux)
  become: true
  when: ansible_facts['system'] == "Linux"
  ansible.builtin.package:
    name: "{{ common_packages }}"
    state: present

- name: Perform packages for specific distribution
  include_tasks: "{{ ansible_facts['distribution'] | lower | replace(' ', '_') }}.yml"

- name: Check if oh my zsh is already installed
  become: false
  ansible.builtin.stat:
    path: "{{ home_dir }}/.oh-my-zsh"
  register: omz_directory_check

- name: Set a variable based on directory's existence
  set_fact:
    omz_directory_exists: "{{ omz_directory_check.stat.exists and omz_directory_check.stat.isdir }}"

- name: Install Oh My Zsh # noqa: latest
  become: false
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ home_dir }}/.oh-my-zsh"
    depth: 1
  when: not omz_directory_exists


- name: Install zsh-autosuggestions plugin # noqa: latest
  become: false
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    depth: 1

- name: Install zsh-syntax-highlighting plugin # noqa: latest
  become: false
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    depth: 1

- name: Install you-should-use plugin # noqa: latest
  become: false
  ansible.builtin.git:
    repo: https://github.com/MichaelAquilina/zsh-you-should-use.git
    dest: "{{ home_dir }}/.oh-my-zsh/custom/plugins/you-should-use"
    depth: 1

- name: Change shell to zsh
  user:
    name: "{{ original_user }}" # Get the current user (more on this below)
    shell: /bin/zsh
    update_password: on_create # On creating the user, set the password


# vimrc
- name: Install vimrc # noqa: latest
  become: false
  ansible.builtin.git:
    repo: https://github.com/amix/vimrc.git
    dest: "{{ home_dir }}/.vim_runtime"
    depth: 1

# Enable vimrc in .vimrc :
- name: Enable vimrc in .vimrc
  blockinfile:
    path: "{{ home_dir }}/.vimrc"
    block: |
      set runtimepath+=~/.vim_runtime

      source ~/.vim_runtime/vimrcs/basic.vim
      source ~/.vim_runtime/vimrcs/filetypes.vim
      source ~/.vim_runtime/vimrcs/plugins_config.vim
      source ~/.vim_runtime/vimrcs/extended.vim
      try
        source ~/.vim_runtime/my_configs.vim
      catch
      endtry
    marker: "\" {mark} ANSIBLE MANAGED BLOCK - vimrc"
    insertafter: EOF
    create: true
  become: false


- name: Install p10k theme # noqa: latest
  become: false
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ home_dir }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1
